services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Linderp\SuluIndexNowBundle\:
        resource: '../../'
        exclude:
          - '../../Resources/'
    Linderp\SuluIndexNowBundle\Subscriber\PersistPageEventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    Sulu\Bundle\WebsiteBundle\Sitemap\SitemapProviderPoolInterface:
        alias: sulu_website.sitemap.pool
